#!/usr/bin/python

import sys
from device_info import get_serial

if __name__ == '__main__':
    name = sys.argv[1]

    try:
        print(get_serial(name))
    except:
        print("Unknown device name: '%s'" % name)
        sys.exit(-1)
