#!/usr/bin/env python

import argparse
import device_info


def _get_state(args):
    print(device_info.get_state(device_info.get_serial(args.name)))


def _get_serial(args):
    print(device_info.get_serial(args.name))


def _get_power(args):
    print(device_info.get_power(args.name))


def _get_parser():
    parser = argparse.ArgumentParser(
        description='Get information about a device')
    sub = parser.add_subparsers(title='Commands', metavar='')
    serial = sub.add_parser('serial', help='Get serial for a device name')
    serial.set_defaults(func=_get_serial)
    serial.add_argument('name', help='Device name')
    power = sub.add_parser('power', help='Get power control info for a device')
    power.set_defaults(func=_get_power)
    power.add_argument('name', help='Device name')
    state = sub.add_parser('state', help='Get device state for a device')
    state.set_defaults(func=_get_state)
    state.add_argument('name', help='Device name')
    return parser


if __name__ == '__main__':
    args = _get_parser().parse_args()
    exit(args.func(args))
