#!/usr/bin/python

import argparse
import logging
import os
import subprocess
import time

from phabletutils.device import AndroidBridge

EMULATOR = os.environ.get('USE_EMULATOR', '')


def _get_arg_parser():
    parser = argparse.ArgumentParser(
        description='Reboot device and waits for networking to become active.')
    parser.add_argument('-s', '--serial', help='Device serial')
    parser.add_argument('-n', '--num-tries', type=int, default=3,
                        help='''How many times to retry on failure.
                             default=%(default)d''')
    return parser


def main(args):
    device = AndroidBridge(args.serial)
    device.wait_for_device()
    for i in range(args.num_tries):
        device.reboot()
        device.wait_for_device()
        time.sleep(5)
        device.wait_for_device()
        try:
            device.wait_for_network()
            return 0
        except:
            pass  # try the loop again
    logging.error('device failed to start and activate networking')
    return 1


def emulator_main(args):
    emulator = os.path.join(os.path.dirname(__file__), 'run-emulator')
    subprocess.check_call([emulator])


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    logging.getLogger().name = 'reboot-and-wait'
    args = _get_arg_parser().parse_args()
    if EMULATOR:
        logging.info('using emulator logic for reboot')
        exit(emulator_main(args))
    else:
        exit(main(args))
