#!/bin/bash

## Executes the new "mega" job. Which provisions and runs all tests in one pass
## Important variables passed to the script from jenkins are:
##  (these are all optional)
## ANDROID_SERIAL
## IMAGE_TYPE - ie - touch, touch_sf4p
## RESDIR - ie "clientlogs". The directory store results in
## IMAGE_OPT - options to pass the phablet-flash
## INSTALL_URL - value to see if target has proper image in place
## PACKAGES - debian packages to install
## APPS - autopilot apps to run or ALL
## TESTS - UTAH tests to run or ALL
## STATSD_KEY - If provided metrics will be sent to statsd with this prefix

set -e

BASEDIR=$(readlink -f $(dirname $0)/..)

IMAGE_TYPE="${IMAGE_TYPE-touch}"
RESDIR="${RESDIR-$(pwd)/clientlogs}"

add_stat() {
	[ -z $STATSD_KEY ] || ${BASEDIR}/scripts/statsd-cli "${STATSD_KEY}.$1:$2|$3"
}

timeit() {
	rc=0
	start=$(date +%s.%N)
	$* || rc=1
	end=$(date +%s.%N)
	diff=$(echo "($end - $start) * 1000" | bc)
	add_stat $1 $diff ms
	return $rc
}

gaugeit() {
	val=$(eval "echo \$$1" | wc -w)
	add_stat $1 $val g
}

provision() {
	if [ -z $INSTALL_URL ] ; then
		if [ "$PACKAGES" = "ALL" ] ; then
			PACKAGES="$(${BASEDIR}/jenkins/testconfig.py packages -i $IMAGE_TYPE)"
		fi

		custom_args=""
		set +x
		gaugeit PACKAGES
		for p in $PACKAGES ; do
			custom_args="$custom_args -p $p"
		done
		for p in $PPAS ; do
			custom_args="$custom_args -P $p"
		done
		set -x
		${BASEDIR}/scripts/provision.sh -i ${IMAGE_TYPE} $custom_args
	else
		${BASEDIR}/scripts/assert-image
	fi
}

test_autopilot() {
	if [ "$APPS" = "ALL" ] ; then
		APPS="$(${BASEDIR}/jenkins/testconfig.py apps -i $IMAGE_TYPE)"
	fi
	gaugeit APPS
	[ -z "$APPS" ] || APPS=${APPS} ${BASEDIR}/scripts/run-autopilot-tests.sh || return 1
}

test_utah() {
	if [ "$TESTS" = "ALL" ] ; then
		TESTS="$(${BASEDIR}/jenkins/testconfig.py utah -i $IMAGE_TYPE)"
	fi
	gaugeit TESTS

	rc=0
	for test in $TESTS ; do
		echo == testing $test =======================================================
		RESDIR=${RESDIR}/$test ${BASEDIR}/scripts/jenkins.sh -a $test || rc=1
	done
	return $rc
}

main() {
	rc=0
	timeit provision
	timeit test_autopilot || rc=1
	timeit test_utah || rc=1
	return $rc
}

timeit main
