#!/bin/bash

set -e

SERVER=${SERVER-"snakefruit.canonical.com"}
PORT=${PORT-"10041"}

send_msg() {
	exec 3<>/dev/udp/$SERVER/$PORT

	echo $* >&3

	exec 3<&-
	exec 3>&-
}

[ $# -gt 0 ] || (echo "Must provide statsd formatted string" && exit 1)
send_msg $*
