#!/bin/sh


UTAH_PROBE_DIR="${UTAH_PROBE_DIR-/var/cache/utah-probes}"
adb-shell mkdir -p /tmp/xmlresults

adb-shell sudo -i -u phablet bash -ic \"cd /home/phablet/autopilot \; UTAH_PROBE_DIR=$UTAH_PROBES_DIR autopilot run -v -f xml -o /tmp/xmlresults/$*.xml $*\"
