#!/bin/bash
set -e

rc=0

if [ "${ADT_REBOOT_MARK}" == "reboot_mark" ]; then
    ls > "${ADT_ARTIFACTS}"/ls.txt
    rc=$?
else 
    /tmp/autopkgtest-reboot reboot_mark
    echo "Are we having fun yet?"
fi
exit $rc
